### ISSUE TITLE
Possible bug: Cleanup function using 'on' instead of 'off' for event listeners

### ISSUE THREAD

**Issue by andrejilderda** [lhapaipai/maplibre-react-components#2]
Hi @lhapaipai ,

I'm looking at different map options and while scanning through the code I noticed a potential issue in the cleanup function of RLayer.tsx on [this line](https://github.com/lhapaipai/maplibre-react-components/blob/129cc8096da23d958199245c5bbb139d99fbc208/src/components/RLayer/RLayer.tsx#L254C11-L254C47):
```typescript
      return () => {
        eventNames.forEach((eventName) => {
          // @ts-ignore
          map.on(eventName, id, onLayerEvent);
        });
      };
```
This appears to be adding event listeners (map.on) in the cleanup function, when it should likely be removing them (map.off). I suggest changing it to:

```typescript
      return () => {
        eventNames.forEach((eventName) => {
          // @ts-ignore
          map.off(eventName, id, onLayerEvent);
        });
      };
```

I haven't test things out, so please correct me if I'm wrong. :)

**Comment by lhapaipai** [comment]
hi @andrejilderda,
Thanks for your feedback, of course you are absolutely right, big mistake on my part. 
Have a good day
