### ISSUE TITLE
`RSource`: map.style is undefined on un/remount

### ISSUE THREAD

**Issue by andrejilderda** [lhapaipai/maplibre-react-components#5]
### maplibre-react-components version

0.1.7

### your OS, React version

macOS, React 18.2.0

### Description

I found a case where an `Uncaught TypeError: map.style is undefined`-error is thrown for [this line](https://github.com/lhapaipai/maplibre-react-components/blob/c786683469955f14005e833c5291e8a4951be39e/src/components/RSource/RSource.tsx#L156) when a map containing a `RSource` and/or `RLayer` was remounting. As the error implies the `style` property on `map` is accessed but not defined at that moment.

### How to reproduce

I have tried to create a small reproduction in Storybook that was very similar to my setup, but unfortunately couldn't trigger the error.

### Possible Solution

🕊️ PR incoming.

**Comment by lhapaipai** [comment]
thanks @andrejilderda, fix is available in v0.1.8
Have a good evening !
